# basemap.at source definitions
# https://basemap.at

sources:
  basemap_at_wmts:
    type: wmts
    url_template: "https://basemap.at/wmts/1.0.0/geolandbasemap/normal/google3857/{z}/{y}/{x}.png"
    attribution: "© basemap.at, CC-BY 4.0"
    rate_limit_ms: 150
    max_threads: 4
